version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # Uncomment if you serve behind a reverse proxy and need real IPs
    # environment:
    #   - NGINX_REAL_IP_FROM=0.0.0.0/0
